id: P009388
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC20
  title: ཕར་ཕྱིན་སྐབས་བཞི་པའི་སྡོམ་འགྲེལ་དང་ཤེས་ཁྱད་བྱེད་ངོའི་མཚན་ཉིད་བཞིའི་རྣམ་གཞག
  author: ''
  volumes:
    8107ca3463d344a482be4ac05966306a:
      image_group_id: I2PD18430
      title: ''
      volume_number: 1
      total_pages: 358
